
name: Run the bot

on: 
  #push 
  workflow_dispatch: # this is a nice option that will enable a button w/ inputs
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
  schedule:
    - cron:  '0 */2 * * *'


jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install parallel -y 
    - run: mkdir ~/.parallel ; touch ~/.parallel/will-cite

    - name: checkout repo content
      uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'

    
    - run: pip install -r requirements.txt

    - name: run the script
      run: |
        python3 monitor.py; cd output; cat *txt | parallel ../git_clone_repo_within_user_dir.sh
        
      env:
        WEBHOOK: ${{ secrets.WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUERIES_JSON: ${{ secrets.QUERIES_JSON }}

    - name: create archive
      run: tar czf output.tgz output

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output.tgz
        path: output.tgz

